# Generated by Django 3.2.1 on 2021-05-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=3, verbose_name='елемент')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.AddField(
            model_name='elements',
            name='description',
            field=models.CharField(default='Описание отсутствует', max_length=256, verbose_name='Описание'),
        ),
    ]
