# Generated by Django 3.2.1 on 2021-05-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageapp', '0002_auto_20210504_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='row',
            field=models.PositiveIntegerField(default=0, verbose_name='строка'),
        ),
        migrations.AlterField(
            model_name='table',
            name='element',
            field=models.CharField(max_length=3, verbose_name='элемент'),
        ),
    ]
